[terminal.shell]
program = "/usr/sbin/zsh"

[font]
size = 12.0

[font.bold]
family = "Victor Mono"
style = "Bold"

[font.bold_italic]
family = "Victor Mono"
style = "Bold Italic"

[font.italic]
family = "Victor Mono"
style = "Italic"

[font.normal]
family = "VictorMono Nerd Font"
style = "Regular"

[terminal]

[window]
opacity = 0.9
blur = true
